// src/lib.rs

pub mod tool;
pub mod selector;
pub mod click_tool;
pub mod type_tool;
pub mod close_tool;
pub mod extract_tool;
pub mod wait_tool;
pub mod wait_for_element_tool;
pub mod double_click_tool;
pub mod right_click_tool;
pub mod key_press_tool;
pub mod move_mouse_tool;
pub mod drag_drop_tool;
pub mod condition_tool;
pub mod retry_tool;
pub mod read_file_tool;
pub mod write_file_tool;
pub mod screenshot_tool;
pub mod tool_registry;
pub mod selector_recorder;
pub mod highlight;
pub mod highlight_overlay;
pub mod app_launcher;

// Экспортируем для удобства использования в примерах
pub use tool::{Tool, ExecutionContext};
pub use selector::Selector;
pub use click_tool::ClickTool;
pub use type_tool::TypeTool;
pub use close_tool::CloseTool;
pub use extract_tool::ExtractTool;
pub use wait_tool::WaitTool;
pub use wait_for_element_tool::WaitForElementTool;
pub use double_click_tool::DoubleClickTool;
pub use right_click_tool::RightClickTool;
pub use key_press_tool::KeyPressTool;
pub use move_mouse_tool::MoveMouseTool;
pub use drag_drop_tool::DragDropTool;
pub use condition_tool::ConditionTool;
pub use retry_tool::RetryTool;
pub use read_file_tool::ReadFileTool;
pub use write_file_tool::WriteFileTool;
pub use screenshot_tool::ScreenshotTool;
pub use tool_registry::ToolRegistry;
pub use selector_recorder::{SelectorRecorder, RecordedSelector, SelectorStep, ElementProperties, is_electron_element};
pub use highlight::{HighlightConfig, highlight_element, highlight_element_animated, highlight_selector_tree};
pub use highlight_overlay::{draw_highlight_rect_async, draw_highlight_rect_blocking, draw_highlight_rect_animated, draw_highlight_rect_track_cursor, get_dpi_scale, scale_rect, ensure_dpi_aware};
pub use app_launcher::{find_executable, launch_app, launch_app_and_wait, parse_app_arg};